name: Auto Release with Version Bump

on:
  push:
    branches:
      - main

permissions: write-all

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository with tags
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Generate GitHub App Token
        id: generate_token
        uses: peter-murray/workflow-application-token-action@v3
        with:
          application_id: ${{ vars.APP_ID }}
          application_private_key: ${{ secrets.APP_PRIVATE_KEY }}

      - name: Read version from index.json
        id: read_version
        run: |
          VERSION=$(jq -r '.version' index.json)
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Install registry-signer
        run: |
          curl -s https://api.github.com/repos/IES-parquesol-package-registry/registry-signer/releases/latest | jq -r '.assets[0].browser_download_url' | xargs -I {} curl -L -o registry-signer {}

      - name: Make registry-signer executable
        run: chmod +x registry-signer

      - name: Sign the registry file
        run: ./registry-signer --file index.json --sign ${{ secrets.SIGNING_KEY }}

      - name: Create new tag
        id: tag
        run: |
          VERSION=${{ steps.read_version.outputs.version }}
          # Verificar si el tag ya existe
          if git rev-parse "$VERSION" >/dev/null 2>&1; then
            echo "Tag $VERSION already exists. Abortando."
            exit 1
          fi
          git tag "$VERSION"
          git push origin "$VERSION"

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.read_version.outputs.version }}
          name: "Release ${{ steps.read_version.outputs.version }}"
          body: "Release automática. Versión actualizada a ${{ steps.read_version.outputs.version }}."
          files: |
            ./index.json
            ./sign.sig
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
