name: Auto Release with Version Bump

on:
  push:
    branches:
      - main

permissions: write-all

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository with tags
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Generate GitHub App Token
        id: generate_token
        uses: peter-murray/workflow-application-token-action@v3
        with:
          application_id: ${{ vars.APP_ID }}
          application_private_key: ${{ secrets.APP_PRIVATE_KEY }}

      - name: Bump version in index.json
        id: bump
        run: |
          # Leer la versión actual desde index.json
          CURRENT_VERSION=$(jq -r '.version' index.json)
          echo "Current version: $CURRENT_VERSION"
          # Quitar la "v" para trabajar solo con números
          VERSION_NUM=${CURRENT_VERSION#v}
          IFS='.' read -r MAJOR MINOR PATCH <<< "$VERSION_NUM"
          # Incrementar la parte de parche
          NEW_PATCH=$((PATCH + 1))
          NEW_VERSION="v${MAJOR}.${MINOR}.${NEW_PATCH}"
          echo "New version: $NEW_VERSION"
          # Actualizar el archivo index.json con la nueva versión
          jq --arg new_version "$NEW_VERSION" '.version = $new_version' index.json > tmp.json && mv tmp.json index.json
          echo "new_version=$NEW_VERSION" >> $GITHUB_OUTPUT

      - name: Commit version bump
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add index.json
          git diff --cached --quiet || git commit -m "Bump version to $NEW_VERSION"
          git remote set-url origin https://x-access-token:${{ steps.generate_token.outputs.token }}@github.com/${{ github.repository }}
          git push origin HEAD:main

      - name: Create new tag
        id: tag
        run: |
          NEW_VERSION=${{ steps.bump.outputs.new_version }}
          # Verificar si el tag ya existe
          if git rev-parse "$NEW_VERSION" >/dev/null 2>&1; then
            echo "Tag $NEW_VERSION already exists. Abortando."
            exit 1
          fi
          git tag "$NEW_VERSION"
          git push origin "$NEW_VERSION"

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.bump.outputs.new_version }}
          name: "Release ${{ steps.bump.outputs.new_version }}"
          body: "Release automática. Versión actualizada a ${{ steps.bump.outputs.new_version }}."
          files: |
            ./registry-signer  # Ajusta la ruta al asset que desees incluir
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
